parameters:
    '%env(resolve:DATABASE_URL)%': "."
doctrine:
    dbal:
        # configure these for your database server
        url: "%env(resolve:DATABASE_URL)%"
    orm:
        auto_generate_proxy_classes: '%kernel.debug%'
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true
        mappings:
            Demo:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Entity'
                prefix: 'Demo\Entity'
                alias: Demo
