language: php

sudo: false

cache:
  directories:
    - $HOME/.composer/cache
    - $HOME/.npm

env:
  global:
    - SYMFONY_DEPRECATIONS_HELPER=weak_vendors
    - APP_ENV=test

matrix:
  include:
    - php: '7.1'
    - php: '7.2'

before_install:
  - echo "memory_limit=-1" >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
  - export PATH="$PATH:$HOME/.composer/vendor/bin"
  - wget https://github.com/satooshi/php-coveralls/releases/download/v1.0.1/coveralls.phar
  - chmod +x coveralls.phar
install:
  - composer update --prefer-dist --no-progress --no-suggest --ansi

script:
  - mkdir -p build/logs
  - bin/phpunit
  - ./vendor/bin/behat -fprogress

after_script:
  - export CI_BUILD_NUMBER="$TRAVIS_BUILD_NUMBER"
  - export CI_PULL_REQUEST="$TRAVIS_PULL_REQUEST"
  - export CI_BRANCH="$TRAVIS_BRANCH"
  - travis_retry php coveralls.phar -v