language: php

sudo: false

cache:
  directories:
    - $HOME/.composer/cache
    - $HOME/.npm

env:
  global:
    - SYMFONY_DEPRECATIONS_HELPER=weak_vendors
    - APP_ENV=test

matrix:
  include:
    - php: '7.1'
    - php: '7.2'

before_install:
  - echo "memory_limit=-1" >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
  - export PATH="$PATH:$HOME/.composer/vendor/bin"

install:
  - composer update --prefer-dist --no-progress --no-suggest --ansi

script:
  - mkdir -p build/logs
  - bin/phpunit
  - ./vendor/bin/phpspec run
  - ./vendor/bin/behat -fprogress

after_success:
  - bash <(curl -s https://codecov.io/bash) -s build/logs -f "*.xml"