customer_controllers:
    resource: ../../src/Customer/Controller/
    type: annotation
    options:
        expose: true

employee_controllers:
    resource: ../../src/Employee/Controller/
    type: annotation
    options:
        expose: true
