core:
    resource: '../src/Core/Resources/routes.yaml'
    prefix: "/api"

#login_check_json:
#    path: /login_check_json
#    method: "POST"
#    controller: Omed\Core\Controller\SecurityController::login
